name: Semantic Release

on:
    push:
        branches:
            - master

jobs:
    build:

        permissions:
            contents: write
            issues: write
            pull-requests: write      

        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Run semantic release
              run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}